INSERT INTO items(name,type,price,description,img) Values
('Sony PS5','Console','550','The PS5 has a brand-new user interface with a number of new features to make jumping into games more streamlined. Apps are divided into two sections — games and media, and if you''re familiar with the PS4''s interface, then the row of app icons in the games menu will look very familiar to you.','https://www.techinn.com/f/13776/137769821/sony-ps5.jpg'),
('Microsoft Xbox Series X','Console','500','The Xbox Series X has higher end hardware, and supports higher display resolutions (up to 8K resolution) along with higher frame rates and real-time ray tracing; it also has a high-speed solid-state drive to reduce loading times.','https://www.techinn.com/f/13777/137776929/microsoft-xbox-series-x-1tb.jpg'),
('Nintendo Switch','Console','300','The Nintendo Switch system transforms from home console to handheld, letting you play your favorite games at home or on the go. It includes a dock for connecting to your TV, as well as removable Joy-Con™ controllers that you can share with a friend for two-player fun.','https://i.gadgets360cdn.com/products/large/1549526400_635_nintendo_switch_db.jpg'),
('HP Omen 15', 'Laptop', '1200', 'Despite being quite a heavy and bulky device with underwhelming battery performance, the HP Omen 15 still has quite a lot to offer, and makes up for it with strong gaming performance, excellent audio design and video quality, along with a great, clear, anti-glare display.', 'https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc3/4_zu_3_omen15.jpg'),
('Lenovo Legion7', 'Laptop', '1500', 'Underneath its refined aerospace-grade aluminum exterior the Legion 7 Gen 6 (16" AMD) gaming laptop harbors a savage engine. Powered by latest-gen AMD processing and NVIDIA® GeForce RTX™ Graphics this beast is AI-optimized with the Lenovo Legion AI Engine.','https://www.lenovo.com/medias/lenovo-laptop-gaming-legion-7-16in-amd-gallery-11.png?context=bWFzdGVyfHJvb3R8MTAzOTg1fGltYWdlL3BuZ3xoOWQvaDRkLzExNDg0MTMyNDA5Mzc0LnBuZ3w5ZTBkYzIwMmU4MjRkMTM1MTIzZjhhZTk2ZjFjNGJjMmQ3YTE5MWFjMzg4Y2RmZDk3YjZkM2E3Nzk0MjdjNjJj'),
('Iphone 12', 'Phone', '1400', 'The iPhone 12 features a 6.1-inch (15 cm) display with Super Retina XDR OLED technology at a resolution of 2532×1170 pixels and a pixel density of about 460 ppi. The iPhone 12 Mini features a 5.4-inch (14 cm) display with the same technology at a resolution of 2340×1080 pixels and a pixel density of about 476 ppi.', 'https://img.router-switch.com/media/customoptions/128/2/6/iphone-12-pro-gray.jpg'),
('Samsung S21', 'Phone', '1600', 'The Galaxy S21 series has a lot of features some of which are hidden. Samsungs Galaxy 21 is out now. All three models look truly impressive, between full 5G support across the lineup, a new camera array and improved camera features. The S21 Ultra even has a new feature for the S-series, with S-Pen stylus support.', 'https://www.mytrendyphone.eu/images/Samsung-Galaxy-S21-5G-128GB-Phantom-Grey-8806090892776-18012021-01-p.jpg'),
('Apple Airpods 2', 'Earphones', '139', 'Powered by the Apple H1 headphone chip AirPods deliver a faster and more stable wireless connection to your devices — up to 2x faster when switching between active devices, and a 1.5x faster connection time for phone calls.', 'https://www.phonefinity.net/wp-content/uploads/airpods-2-2.jpg'),
('Apple M1 MacBook Air 13', 'Laptop', '2400', 'The 2021 MacBook Air will likely feature specs similar to the 2020 model. That includes 8GB of RAM, a 256 or 512 GB SSD, a Retina display with True Tone, Magic Keyboard, Touch ID, and two USB 4.0 ports.', 'https://beytech.com.lb/wp-content/uploads/2021/02/800x800_0013_A.jpg');